name: Matix Demo
on: push 
  # push:
  #   branches: 
  #     - master 
jobs:
  build:
    strategy:
      Matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ Matix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ Matix.node-version }}
      - name: install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build

